packages:
  - "."
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  lefthook: true
  sharp: true
  unrs-resolver: true
overrides:
  react-loader-spinner>react: ^19.2.8
  react-loader-spinner>react-dom: ^19.2.8
  react-scrollbar-size>react: ^19.2.8
  stylelint-css-modules-no-global-scoped-selector>stylelint: 16.26.1
  stylelint-no-unused-selectors>stylelint: 16.26.1
  zod: 3.25.76
